// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Orderdetail.Add;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Orderdetail.Get;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Orderdetail.Job;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Orderdetail.Jobview;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Orderdetail.Move;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Orderdetail.Remove;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Orderdetail {
    /// <summary>
    /// Builds and executes requests for operations under \api2\ServiceProvider\Orderdetail
    /// </summary>
    public class OrderdetailRequestBuilder : BaseRequestBuilder {
        /// <summary>The add property</summary>
        public AddRequestBuilder Add { get =>
            new AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public GetRequestBuilder GetPath { get =>
            new GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The job property</summary>
        public JobRequestBuilder Job { get =>
            new JobRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobview property</summary>
        public JobviewRequestBuilder Jobview { get =>
            new JobviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The move property</summary>
        public MoveRequestBuilder Move { get =>
            new MoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remove property</summary>
        public RemoveRequestBuilder Remove { get =>
            new RemoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new OrderdetailRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderdetailRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api2/ServiceProvider/Orderdetail", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new OrderdetailRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderdetailRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api2/ServiceProvider/Orderdetail", rawUrl) {
        }
    }
}
