// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Scheduler.DateRange;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Scheduler.Events;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Scheduler.Resources;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Scheduler {
    /// <summary>
    /// Builds and executes requests for operations under \api2\ServiceProvider\Scheduler
    /// </summary>
    public class SchedulerRequestBuilder : BaseRequestBuilder {
        /// <summary>The DateRange property</summary>
        public DateRangeRequestBuilder DateRange { get =>
            new DateRangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Events property</summary>
        public EventsRequestBuilder Events { get =>
            new EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Resources property</summary>
        public ResourcesRequestBuilder Resources { get =>
            new ResourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new SchedulerRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchedulerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api2/ServiceProvider/Scheduler", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new SchedulerRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchedulerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api2/ServiceProvider/Scheduler", rawUrl) {
        }
    }
}
