// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Kpi.CompletedJobs;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Kpi.Job;
using Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Kpi.TimeReport;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Qwips.SmartService.ServiceProvider.ClientSdk.Api2.Serviceprovider.Kpi {
    /// <summary>
    /// Builds and executes requests for operations under \api2\ServiceProvider\Kpi
    /// </summary>
    public class KpiRequestBuilder : BaseRequestBuilder {
        /// <summary>The CompletedJobs property</summary>
        public CompletedJobsRequestBuilder CompletedJobs { get =>
            new CompletedJobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The job property</summary>
        public JobRequestBuilder Job { get =>
            new JobRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The TimeReport property</summary>
        public TimeReportRequestBuilder TimeReport { get =>
            new TimeReportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new KpiRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KpiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api2/ServiceProvider/Kpi", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new KpiRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KpiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api2/ServiceProvider/Kpi", rawUrl) {
        }
    }
}
