// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Qwips.SmartService.ServiceProvider.ClientSdk.Models {
    public class JobStatusDto : IParsable {
        /// <summary>The Count property</summary>
        public int? Count { get; set; }
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The JobSubStatuses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<JobSubStatusDto>? JobSubStatuses { get; set; }
#nullable restore
#else
        public List<JobSubStatusDto> JobSubStatuses { get; set; }
#endif
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The SortOrder property</summary>
        public int? SortOrder { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static JobStatusDto CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new JobStatusDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"Count", n => { Count = n.GetIntValue(); } },
                {"Id", n => { Id = n.GetIntValue(); } },
                {"JobSubStatuses", n => { JobSubStatuses = n.GetCollectionOfObjectValues<JobSubStatusDto>(JobSubStatusDto.CreateFromDiscriminatorValue)?.ToList(); } },
                {"Name", n => { Name = n.GetStringValue(); } },
                {"SortOrder", n => { SortOrder = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("Count", Count);
            writer.WriteIntValue("Id", Id);
            writer.WriteCollectionOfObjectValues<JobSubStatusDto>("JobSubStatuses", JobSubStatuses);
            writer.WriteStringValue("Name", Name);
            writer.WriteIntValue("SortOrder", SortOrder);
        }
    }
}
